FROM apache/airflow:2.9.2
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt
USER root
RUN apt-get update && \
    apt-get -y install git && \
    apt-get install -y procps && \
    apt-get install -y default-jre && \
    apt-get clean

USER airflow